package grisu.frontend.view.swing.jobmonitoring.single;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import grisu.control.ServiceInterface;
import grisu.frontend.control.login.LoginManager;
import grisu.jcommons.constants.Constants;
import grisu.jcommons.utils.swing.LogPanel;

import javax.swing.*;
import java.awt.*;

public class SingleJobTabbedDialog extends JDialog {
    private JPanel contentPane;
    private JButton buttonOK;
    private SingleJobTabbedPane singleJobTabbedPane1;
    private final ServiceInterface si;
    private final String application;
    private LogPanel logPanel;

    public SingleJobTabbedDialog(ServiceInterface si, String application) {
        this.si = si;
        this.application = application;
        $$$setupUI$$$();
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);
    }

    public static void main(String[] args) throws Exception {

        ServiceInterface si = LoginManager.login("bestgrid");
        String application = Constants.ALLJOBS_KEY;
        SingleJobTabbedDialog dialog = new SingleJobTabbedDialog(si, Constants.ALLJOBS_KEY);
        dialog.pack();
        dialog.setVisible(true);
        System.exit(0);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        logPanel = new LogPanel();
        singleJobTabbedPane1 = new SingleJobTabbedPane(si, application);
        singleJobTabbedPane1.addTab("Monitor log", logPanel, 0);
        setTitle("Monitoring: " + application);

    }

    public void addMessage(String msg) {
        logPanel.addMessage(msg);
    }

    public void addError(String msg) {
        logPanel.addWarningMessage(msg);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.add(singleJobTabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
